CREATE TABLE "ATG_3731_WO_SIGN_LOG"(
 "JOB" CHAR(6) NOT NULL ,
 "SUFFIX" CHAR(3) NOT NULL ,
 "SEQUENCE" CHAR(6) NOT NULL ,
 "DESCRIPTION" CHAR(30) NOT NULL ,
 "GSUser" CHAR(8) NOT NULL ,
 "TaskSignOffDate" DATETIME NOT NULL ,
 "ReportNo" VARCHAR(50) NOT NULL );